from __future__ import annotations

import hashlib
import hmac
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

from fastapi import HTTPException, Request, status
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import JSONResponse

from app.core.config import get_settings


@dataclass(frozen=True)
class AuthStatus:
    enabled: bool
    token_configured: bool
    required: bool
    source: str
    bootstrap_open: bool
    updated_at: str | None = None
    env_forced_enabled: bool = False


PROTECTED_PREFIXES = (
    "/api/eox",
    "/api/setup",
    "/api/logs",
    "/api/export",
    "/api/autopop",
    "/graphql",
)

OPEN_PATHS = (
    "/api/auth/status",
    "/api/auth/bootstrap",
    "/api/auth/verify",
    "/api/setup/status",
    "/api/health",
    "/health",
    "/docs",
    "/redoc",
    "/openapi.json",
)


def auth_config_path() -> Path:
    settings = get_settings()
    return Path(os.getenv("EOX_AUTH_CONFIG_FILE", settings.data_dir / ".eox_auth.env"))


def _parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def _write_env_file(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by Cisco EOX Manager security setup UI."]
    for key, value in values.items():
        lines.append(f"{key}={value}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _hash_token(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def _env_truthy(value: str | None) -> bool:
    return (value or "").strip().lower() in {"1", "true", "yes", "on"}


def _configured_hash() -> tuple[str | None, str, str | None]:
    if os.getenv("EOX_ADMIN_TOKEN_HASH"):
        return os.getenv("EOX_ADMIN_TOKEN_HASH"), "environment-hash", None
    if os.getenv("EOX_ADMIN_TOKEN"):
        return _hash_token(os.getenv("EOX_ADMIN_TOKEN", "")), "environment-token", None
    path = auth_config_path()
    values = _parse_env_file(path)
    if values.get("EOX_ADMIN_TOKEN_HASH"):
        return values["EOX_ADMIN_TOKEN_HASH"], "runtime-auth-file", values.get("EOX_AUTH_UPDATED_AT")
    return None, "not-configured", None


def auth_enabled() -> bool:
    # Environment true is a hard-enable for deployments that want immutable
    # protection. A runtime auth file can also enable auth from the GUI even
    # when docker-compose defaulted EOX_AUTH_ENABLED=false.
    if _env_truthy(os.getenv("EOX_AUTH_ENABLED")):
        return True
    values = _parse_env_file(auth_config_path())
    return _env_truthy(values.get("EOX_AUTH_ENABLED"))


def get_auth_status() -> AuthStatus:
    token_hash, source, updated_at = _configured_hash()
    enabled = auth_enabled()
    token_configured = bool(token_hash)
    bootstrap_open = enabled and not token_configured
    return AuthStatus(
        enabled=enabled,
        token_configured=token_configured,
        required=enabled and token_configured,
        source=source,
        bootstrap_open=bootstrap_open,
        updated_at=updated_at,
        env_forced_enabled=_env_truthy(os.getenv("EOX_AUTH_ENABLED")),
    )


def save_admin_token(token: str, *, enable_auth: bool = True) -> AuthStatus:
    clean = (token or "").strip()
    if len(clean) < 12:
        raise ValueError("Admin token must be at least 12 characters long")
    path = auth_config_path()
    updated_at = datetime.now(timezone.utc).isoformat()
    _write_env_file(
        path,
        {
            "EOX_AUTH_UPDATED_AT": updated_at,
            "EOX_AUTH_ENABLED": "true" if enable_auth else "false",
            "EOX_ADMIN_TOKEN_HASH": _hash_token(clean),
        },
    )
    return get_auth_status()


def set_runtime_auth_enabled(enabled: bool) -> AuthStatus:
    path = auth_config_path()
    values = _parse_env_file(path)
    values["EOX_AUTH_UPDATED_AT"] = datetime.now(timezone.utc).isoformat()
    values["EOX_AUTH_ENABLED"] = "true" if enabled else "false"
    _write_env_file(path, values)
    return get_auth_status()


def extract_token(request: Request) -> str | None:
    auth_header = request.headers.get("authorization") or ""
    if auth_header.lower().startswith("bearer "):
        return auth_header.split(" ", 1)[1].strip()
    header_token = request.headers.get("x-eox-admin-token")
    if header_token:
        return header_token.strip()
    return None


def verify_token(token: str | None) -> bool:
    status_data = get_auth_status()
    if not status_data.enabled:
        return True
    token_hash, _source, _updated_at = _configured_hash()
    if not token_hash:
        return True
    if not token:
        return False
    return hmac.compare_digest(_hash_token(token.strip()), token_hash)


def is_open_path(path: str, open_paths: Iterable[str] = OPEN_PATHS) -> bool:
    return any(path == item or path.startswith(f"{item}/") for item in open_paths)


def is_protected_path(path: str, protected_prefixes: Iterable[str] = PROTECTED_PREFIXES) -> bool:
    return any(path == item or path.startswith(f"{item}/") for item in protected_prefixes)


async def require_admin(request: Request) -> None:
    if not verify_token(extract_token(request)):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Admin token required")


class AdminAuthMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        if request.method == "OPTIONS":
            return await call_next(request)
        path = request.url.path
        if is_open_path(path) or not is_protected_path(path):
            return await call_next(request)
        if verify_token(extract_token(request)):
            return await call_next(request)
        return JSONResponse(
            {
                "detail": "Admin token required. Open Security in the GUI or send Authorization: Bearer <token> / X-EOX-Admin-Token.",
                "auth_required": True,
            },
            status_code=status.HTTP_401_UNAUTHORIZED,
        )
