from __future__ import annotations

import json
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import quote_plus

from app.core.config import get_settings


@dataclass(frozen=True)
class RuntimeConfig:
    database_url: str | None = None
    database_source: str = "environment"
    updated_at: str | None = None


def runtime_config_path() -> Path:
    settings = get_settings()
    return Path(os.getenv("EOX_RUNTIME_CONFIG_FILE", settings.data_dir / "runtime_config.json"))


def env_export_path() -> Path:
    settings = get_settings()
    return Path(os.getenv("EOX_ENV_EXPORT_FILE", settings.data_dir / ".env.local"))


def read_runtime_config() -> RuntimeConfig:
    path = runtime_config_path()
    if not path.exists():
        return RuntimeConfig()
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return RuntimeConfig()
    return RuntimeConfig(
        database_url=raw.get("database_url") or None,
        database_source=raw.get("database_source") or "runtime-file",
        updated_at=raw.get("updated_at"),
    )


def write_runtime_database_url(database_url: str, *, write_env_file: bool = True) -> RuntimeConfig:
    path = runtime_config_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "database_url": database_url,
        "database_source": "runtime-file",
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    if write_env_file:
        write_env_export(database_url)
    return read_runtime_config()


def write_env_export(database_url: str) -> Path:
    path = env_export_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# Generated by Cisco EOX Manager setup UI.\n"
        "# Docker Compose still needs a restart to consume this file directly.\n"
        f"EOX_DATABASE_URL={database_url}\n",
        encoding="utf-8",
    )
    return path


def effective_database_url() -> str:
    runtime = read_runtime_config()
    if runtime.database_url:
        return runtime.database_url
    return get_settings().database_url


def database_url_hint(value: str | None = None) -> str:
    url = value or effective_database_url()
    if not url:
        return ""
    masked = url
    if "://" in masked and "@" in masked:
        scheme, rest = masked.split("://", 1)
        credentials, host = rest.split("@", 1)
        if ":" in credentials:
            user, _password = credentials.split(":", 1)
            masked = f"{scheme}://{user}:****@{host}"
    return masked


def build_postgres_url(*, host: str, port: int, database: str, username: str, password: str) -> str:
    safe_user = quote_plus(username)
    safe_password = quote_plus(password)
    safe_host = host.strip() or "db"
    safe_database = database.strip() or "eox_cache"
    safe_port = int(port or 5432)
    return f"postgresql+psycopg://{safe_user}:{safe_password}@{safe_host}:{safe_port}/{safe_database}"
