import os
import shutil
import pandas as pd

def append_to_excel(ticket_number, data_list, file_path="pm.report.xlsx", column_order=None):
    column_order = [
                'File name', 'Host name', 'Model number', 'Serial number', 'Interface ip address',
                'Uptime', 'Current s/w version', 'Current SW EOS', 'Suggested s/w ver', 's/w release date',
                'Latest S/W version', 'Production s/w is deffered or not?', 'Last Reboot Reason', 'Any Debug?',
                'CPU Utilization', 'Total memory', 'Used memory', 'Free memory', 'Memory Utilization (%)',
                'Total flash memory', 'Used flash memory', 'Free flash memory', 'Used Flash (%)',
                'Fan status', 'Temperature status', 'PowerSupply status', 'Available Free Ports',
                'End-of-Sale Date: HW', 'Last Date of Support: HW', 'End of Routine Failure Analysis Date: HW',
                'End of Vulnerability/Security Support: HW', 'End of SW Maintenance Releases Date: HW',
                'Any Half Duplex', 'Interface/Module Remark', 'Config Status', 'Config Save Date',
                'Critical logs', 'Remark'
            ]

    # Create a list to store the formatted data
    formatted_data = []

    # Iterate over the data list
    for data in data_list:
        # Determine the length of the data
        data_length = len(next(iter(data.values())))

        # Iterate over the data
        for i in range(data_length):
            row_data = {}
            for key in column_order:
                if key in data:
                    value = data[key]
                    if isinstance(value, list):
                        row_data[key] = value[i]
                    else:
                        row_data[key] = value
                else:
                    row_data[key] = 'NA'
            formatted_data.append(row_data)

    # Create a DataFrame
    df = pd.DataFrame(formatted_data)

    # Reorder the columns
    df = df[column_order]

    # Write to Excel
    try:
        existing_df = pd.read_excel(file_path)
        combined_df = pd.concat([existing_df, df])
        combined_df.to_excel(file_path, index=False)
    except FileNotFoundError:
        df.to_excel(file_path, index=False)

def main():
    try:
        SVR = "SVR"
        data_list = []
        # Assuming you have a list of data dictionaries
        data1 = {'Any Debug?': ['Command not found.',
                'Command not found.',
                'Command not found.'],
 'Any Half Duplex': [[0], [2], [1]],
 'Available Free Ports': [[3], [3], [4]],
 'CPU Utilization': ['2%', '2%', '2%'],
 'Config Save Date': ['18:24:53 MYT Tue Jan 23 2024',
                      '18:24:53 MYT Tue Jan 23 2024',
                      '18:24:53 MYT Tue Jan 23 2024'],
 'Config Status': ['Yes', 'Yes', 'Yes'],
 'Critical logs': ['NO', 'NO', 'NO'],
 'Current SW EOS': ['Yet to check', 'Yet to check', 'Yet to check'],
 'Current s/w version': ['17.06.04', '17.06.04', '17.06.04'],
 'End of Routine Failure Analysis Date: HW': ['Yet to check',
                                              'Yet to check',
                                              'Yet to check'],
 'End of SW Maintenance Releases Date: HW': ['Yet to check',
                                             'Yet to check',
                                             'Yet to check'],
 'End of Vulnerability/Security Support: HW': ['Yet to check',
                                               'Yet to check',
                                               'Yet to check'],
 'End-of-Sale Date: HW': ['Yet to check', 'Yet to check', 'Yet to check'],
 'Fan status': ['OK', 'OK', 'OK'],
 'File name': ['UOBAM-C9300-PLA-L20-DSW-01_10.52.254.5.txt',
               'UOBAM-C9300-PLA-L20-DSW-01_10.52.254.5.txt_Stack_2',
               'UOBAM-C9300-PLA-L20-DSW-01_10.52.254.5.txt_Stack_3'],
 'Free flash memory': [7026290688, 7027556352, 7027556352],
 'Free memory': [1021725796, 1021725796, 1021725796],
 'Host name': ['UOBAM-C9300-PLA-L20-DSW-01',
               'UOBAM-C9300-PLA-L20-DSW-01',
               'UOBAM-C9300-PLA-L20-DSW-01'],
 'Interface ip address': ['10.52.254.5', '10.52.254.5', '10.52.254.5'],
 'Interface/Module Remark': [['N/A'], ['Gi2/0/4', 'Ap2/0/1'], ['Ap3/0/1']],
 'Last Date of Support: HW': ['Yet to check', 'Yet to check', 'Yet to check'],
 'Last Reboot Reason': ['PowerOn', 'PowerOn', 'PowerOn'],
 'Latest S/W version': ['Yet to check', 'Yet to check', 'Yet to check'],
 'Memory Utilization (%)': ['24.24%', '24.24%', '24.24%'],
 'Model number': ['C9300L-48P-4X', 'C9300L-48P-4X', 'C9300L-48P-4X'],
 'PowerSupply status': ['OK', 'OK', 'OK'],
 'Production s/w is deffered or not?': ['Yet to check',
                                        'Yet to check',
                                        'Yet to check'],
 'Remark': ['Yet to check', 'Yet to check', 'Yet to check'],
 'Serial number': ['FOC2714Z5D6', 'FOC2714Z5LJ', 'FOC2715Y1FY'],
 'Suggested s/w ver': ['Yet to check', 'Yet to check', 'Yet to check'],
 'Temperature status': ['OK', 'OK', 'OK'],
 'Total flash memory': [10776477696, 10777264128, 10777264128],
 'Total memory': [1348568636, 1348568636, 1348568636],
 'Uptime': ['1 year, 46 weeks, 5 days, 18 hours, 5 minutes',
            '1 year, 46 weeks, 5 days, 17 hours, 58 minutes',
            '1 year, 46 weeks, 5 days, 18 hours, 7 minutes'],
 'Used Flash (%)': ['34.80%', '34.79%', '34.79%'],
 'Used flash memory': [3750187008, 3749707776, 3749707776],
 'Used memory': [326842840, 326842840, 326842840],
 's/w release date': ['Yet to check', 'Yet to check', 'Yet to check']}
        
        data2 = {'Any Debug?': ['Command not found.',
                'Command not found.',
                'Command not found.',
                'Command not found.',
                'Command not found.',
                'Command not found.',
                'Command not found.',
                'Command not found.'],
 'Any Half Duplex': ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
 'Available Free Ports': [[2], [4], [4], [4], [4], [4], [4], [2]],
 'CPU Utilization': ['7%', '7%', '7%', '7%', '7%', '7%', '7%', '7%'],
 'Config Save Date': ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA'],
 'Config Status': ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'],
 'Critical logs': ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
 'Current SW EOS': ['Yet to check',
                    'Yet to check',
                    'Yet to check',
                    'Yet to check',
                    'Yet to check',
                    'Yet to check',
                    'Yet to check',
                    'Yet to check'],
 'Current s/w version': ['17.09.05',
                         '17.09.05',
                         '17.09.05',
                         '17.09.05',
                         '17.09.05',
                         '17.09.05',
                         '17.09.05',
                         '17.09.05'],
 'End of Routine Failure Analysis Date: HW': ['Yet to check',
                                              'Yet to check',
                                              'Yet to check',
                                              'Yet to check',
                                              'Yet to check',
                                              'Yet to check',
                                              'Yet to check',
                                              'Yet to check'],
 'End of SW Maintenance Releases Date: HW': ['Yet to check',
                                             'Yet to check',
                                             'Yet to check',
                                             'Yet to check',
                                             'Yet to check',
                                             'Yet to check',
                                             'Yet to check',
                                             'Yet to check'],
 'End of Vulnerability/Security Support: HW': ['Yet to check',
                                               'Yet to check',
                                               'Yet to check',
                                               'Yet to check',
                                               'Yet to check',
                                               'Yet to check',
                                               'Yet to check',
                                               'Yet to check'],
 'End-of-Sale Date: HW': ['Yet to check',
                          'Yet to check',
                          'Yet to check',
                          'Yet to check',
                          'Yet to check',
                          'Yet to check',
                          'Yet to check',
                          'Yet to check'],
 'Fan status': ['Not OK', 'OK', 'Not OK', 'OK', 'OK', 'OK', 'OK', 'OK'],
 'File name': ['PROD029FLOORSW01_172.16.3.29.txt',
               'PROD029FLOORSW01_172.16.3.29.txt_Stack_2',
               'PROD029FLOORSW01_172.16.3.29.txt_Stack_3',
               'PROD029FLOORSW01_172.16.3.29.txt_Stack_4',
               'PROD029FLOORSW01_172.16.3.29.txt_Stack_5',
               'PROD029FLOORSW01_172.16.3.29.txt_Stack_6',
               'PROD029FLOORSW01_172.16.3.29.txt_Stack_7',
               'PROD029FLOORSW01_172.16.3.29.txt_Stack_8'],
 'Free flash memory': [301805568,
                       298582016,
                       332398592,
                       328728576,
                       332398592,
                       276824064,
                       332398592,
                       328466432],
 'Free memory': [398329132,
                 398329132,
                 398329132,
                 398329132,
                 398329132,
                 398329132,
                 398329132,
                 398329132],
 'Host name': ['PROD029FLOORSW01',
               'PROD029FLOORSW01',
               'PROD029FLOORSW01',
               'PROD029FLOORSW01',
               'PROD029FLOORSW01',
               'PROD029FLOORSW01',
               'PROD029FLOORSW01',
               'PROD029FLOORSW01'],
 'Interface ip address': ['172.16.3.29',
                          '172.16.3.29',
                          '172.16.3.29',
                          '172.16.3.29',
                          '172.16.3.29',
                          '172.16.3.29',
                          '172.16.3.29',
                          '172.16.3.29'],
 'Interface/Module Remark': ['N/A',
                             'N/A',
                             'N/A',
                             'N/A',
                             'N/A',
                             'N/A',
                             'N/A',
                             'N/A'],
 'Last Date of Support: HW': ['Yet to check',
                              'Yet to check',
                              'Yet to check',
                              'Yet to check',
                              'Yet to check',
                              'Yet to check',
                              'Yet to check',
                              'Yet to check'],
 'Last Reboot Reason': ['Power Failure or Unknown',
                        'Power Failure or Unknown',
                        'Power Failure or Unknown',
                        'Power Failure or Unknown',
                        'Power Failure or Unknown',
                        'Power Failure or Unknown',
                        'Power Failure or Unknown',
                        'Power Failure or Unknown'],
 'Latest S/W version': ['Yet to check',
                        'Yet to check',
                        'Yet to check',
                        'Yet to check',
                        'Yet to check',
                        'Yet to check',
                        'Yet to check',
                        'Yet to check'],
 'Memory Utilization (%)': ['24.96%',
                            '24.96%',
                            '24.96%',
                            '24.96%',
                            '24.96%',
                            '24.96%',
                            '24.96%',
                            '24.96%'],
 'Model number': ['C9200L-24P-4G',
                  'C9200L-24P-4G',
                  'C9200L-24P-4G',
                  'C9200L-24P-4G',
                  'C9200L-24P-4G',
                  'C9200L-24P-4G',
                  'C9200L-24P-4G',
                  'C9200L-24P-4G'],
 'PowerSupply status': ['OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK'],
 'Production s/w is deffered or not?': ['Yet to check',
                                        'Yet to check',
                                        'Yet to check',
                                        'Yet to check',
                                        'Yet to check',
                                        'Yet to check',
                                        'Yet to check',
                                        'Yet to check'],
 'Remark': ['Yet to check',
            'Yet to check',
            'Yet to check',
            'Yet to check',
            'Yet to check',
            'Yet to check',
            'Yet to check',
            'Yet to check'],
 'Serial number': ['JAE24461XST',
                   'JAE24461X7N',
                   'JAE24461E1A',
                   'JAE24461FD3',
                   'JAE24440WDU',
                   'JAE242732UK',
                   'JAE24441240',
                   'JAE24461EAC'],
 'Suggested s/w ver': ['Yet to check',
                       'Yet to check',
                       'Yet to check',
                       'Yet to check',
                       'Yet to check',
                       'Yet to check',
                       'Yet to check',
                       'Yet to check'],
 'Temperature status': ['OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK'],
 'Total flash memory': [1857437696,
                        1857552384,
                        1857552384,
                        1857552384,
                        1857552384,
                        1857290240,
                        1857552384,
                        1857290240],
 'Total memory': [530788856,
                  530788856,
                  530788856,
                  530788856,
                  530788856,
                  530788856,
                  530788856,
                  530788856],
 'Uptime': ['7 weeks, 1 day, 19 hours, 48 minutes',
            '7 weeks, 1 day, 19 hours, 51 minutes',
            '7 weeks, 1 day, 19 hours, 51 minutes',
            '7 weeks, 1 day, 19 hours, 51 minutes',
            '7 weeks, 1 day, 19 hours, 51 minutes',
            '7 weeks, 1 day, 19 hours, 51 minutes',
            '7 weeks, 1 day, 19 hours, 51 minutes',
            '7 weeks, 1 day, 19 hours, 51 minutes'],
 'Used Flash (%)': ['83.75%',
                    '83.93%',
                    '82.11%',
                    '82.30%',
                    '82.11%',
                    '85.10%',
                    '82.11%',
                    '82.31%'],
 'Used flash memory': [1555632128,
                       1558970368,
                       1525153792,
                       1528823808,
                       1525153792,
                       1580466176,
                       1525153792,
                       1528823808],
 'Used memory': [132459724,
                 132459724,
                 132459724,
                 132459724,
                 132459724,
                 132459724,
                 132459724,
                 132459724],
 's/w release date': ['Yet to check',
                      'Yet to check',
                      'Yet to check',
                      'Yet to check',
                      'Yet to check',
                      'Yet to check',
                      'Yet to check',
                      'Yet to check']}
        
        data_list.append(data1)
        data_list.append(data2)
        # Add more data dictionaries to the list
        append_to_excel("SVR123", data_list)
    except Exception as e:
        print(f"Error in main: {str(e)}")

if __name__ == "__main__":
    main()